image: node:lts

pipelines:
  branches:
    CICD-12:
      - step:
          name: Install dependencies
          working_directory: fa-client-app-private
          script:
            - yarn install
          artifacts:
            - node_modules/**
      - step:
          name: Build and test
          working_directory: fa-client-app-private
          script:
            - yarn build
          artifacts:
            - build/**
      - step:
          name: Deploy
          working_directory: fa-client-app-private
          script:
            - apt-get update
            - apt-get install -y zip
            - zip -r build.zip build
            - apt-get install -y curl
            - echo "Deploying to ${TARGET_ENVIRONMENT}"
            - echo "Using endpoint https://${TARGET_ENVIRONMENT}.fasolutions.com/rs/secure/fa/api/v1.0/upload/clientportalZip"
            - >
              curl -X POST \
              --location "https://fatemplatedev.fasolutions.com/rs/secure/fa/api/v1.0/upload/clientportalZip" \
              -H "fa-token-name: ${API_TOKEN_NAME}" \
              -H "fa-token-value: ${API_TOKEN_VALUE}" \
              -H "Content-Type: application/zip" \
              --data-binary "@build.zip"
  custom:
    manual-deploy:
      - step:
          name: Install dependencies
          working_directory: fa-client-app-private
          script:
            - yarn install
          artifacts:
            - node_modules/**
      - step:
          name: Build and test
          working_directory: fa-client-app-private
          script:
            - yarn build
          artifacts:
            - build/**
      - step:
          name: Deploy
          working_directory: fa-client-app-private
          script:
            - apt-get update
            - apt-get install -y zip
            - zip -r build.zip build
            - apt-get install -y curl
            - echo "Deploying to ${TARGET_ENVIRONMENT}"
            - echo "Using endpoint https://${TARGET_ENVIRONMENT}.fasolutions.com/rs/secure/fa/api/v1.0/upload/clientportalZip"
            - >
              curl -X POST \
              --location "https://fatemplatedev.fasolutions.com/rs/secure/fa/api/v1.0/upload/clientportalZip" \
              -H "fa-token-name: ${API_TOKEN_NAME}" \
              -H "fa-token-value: ${API_TOKEN_VALUE}" \
              -H "Content-Type: application/zip" \
              --data-binary "@build.zip"